### ISSUE TITLE
Add Discord Link to Links Page

### ISSUE THREAD

**Issue by Saeraphinx** [brugr/website#1]
You can get a link to user accounts for discord by using IDs (e.g. your link would be https://discord.com/users/164391222364995584).
A tiny thing but it makes it easier to find with an ID/direct link as well as a username/discrim.

```html
<a href="https://discord.com/users/164391222364995584" class="link">
    <span class="fab fa-discord fa-fw"></span> brugr#0001.
</a>
```
Would be what you want, I think.

**Comment by brugr** [comment]
never really thought about that, just added it in https://github.com/brugr/website/commit/93684ecb290de22ccfbf2956d5bbc4679d596fdc 😄
